// <auto-generated />
using System;
using EddnIndex.Common.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EddnIndexUpdate.Migrations_MariaDB.Migrations
{
    [DbContext(typeof(EDDNContext))]
    [Migration("20260623170628_NonNullBodyNameId")]
    partial class NonNullBodyNameId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EddnIndex.Common.Models.BodyDesignation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BarycentreLength")
                        .HasColumnType("int");

                    b.Property<int?>("ClusterNum")
                        .HasColumnType("int");

                    b.Property<int?>("CometNum")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("DesignationType")
                        .IsRequired()
                        .HasColumnType("enum('Unknown','StellarBarycentre','StellarBody','Belt','AsteroidCluster','Comet','PlanetaryBarycentre','PlanetaryBody','PlanetaryRing','PlanetaryComet','Moon1Barycentre','Moon1Body','Moon1Ring','Moon1Comet','Moon2Barycentre','Moon2Body','Moon2Ring','Moon2Comet','Moon3Barycentre','Moon3Body','Moon3Ring','Moon3Comet')");

                    b.Property<int?>("Moon1Num")
                        .HasColumnType("int");

                    b.Property<int?>("Moon2Num")
                        .HasColumnType("int");

                    b.Property<int?>("Moon3Num")
                        .HasColumnType("int");

                    b.Property<int?>("PlanetNum")
                        .HasColumnType("int");

                    b.Property<int?>("RingNum")
                        .HasColumnType("int");

                    b.Property<int?>("StarNum")
                        .HasColumnType("int");

                    b.Property<int?>("StellarBarycentreLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Designation");

                    b.ToTable("BodyDesignations", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodyInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ArgOfPeriapsis")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("BodyDesignationId")
                        .HasColumnType("int");

                    b.Property<int?>("BodyId")
                        .HasColumnType("int");

                    b.Property<int>("BodyNameId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Inclination")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ParentSetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SemiMajorAxis")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<sbyte>("SemiMajorAxisScale")
                        .HasColumnType("tinyint");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.Property<long?>("SystemNameId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("BodyNameId");

                    b.HasIndex("ParentSetId");

                    b.HasIndex("SystemId", "BodyId");

                    b.HasIndex("BodyNameId", "SystemId", "ParentSetId");

                    b.ToTable("Bodies", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodyName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("BodyNames", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodyNameOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ArgOfPeriapsis")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<string>("BodyDesignation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("BodyID")
                        .HasColumnType("int");

                    b.Property<string>("BodyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BodyType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Inclination")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<string>("SinceVersion")
                        .HasColumnType("longtext");

                    b.Property<long>("SystemAddress")
                        .HasColumnType("bigint");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UntilVersion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.ToTable("BodyNameOverrides", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodySignalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("EntryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SignalCount")
                        .HasColumnType("int");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("SignalType");

                    b.ToTable("BodySignalInfo", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodyLineCount")
                        .HasColumnType("int");

                    b.Property<int?>("BodySignalCount")
                        .HasColumnType("int");

                    b.Property<long?>("CompressedSize")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool?>("IsTest")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LineCount")
                        .HasColumnType("int");

                    b.Property<int?>("NavRouteSystemCount")
                        .HasColumnType("int");

                    b.Property<string>("PrimarySchema")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("PrimarySchemaEventId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessedVersion")
                        .HasColumnType("int");

                    b.Property<int?>("SignalCount")
                        .HasColumnType("int");

                    b.Property<int?>("StationLineCount")
                        .HasColumnType("int");

                    b.Property<int?>("SystemLineCount")
                        .HasColumnType("int");

                    b.Property<long?>("UncompressedSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("FileName");

                    b.HasIndex("PrimarySchemaEventId");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineBody", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<int>("EntryNum")
                        .HasColumnType("int");

                    b.Property<short?>("ArgOfPeriapsisError")
                        .HasColumnType("smallint");

                    b.Property<long>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<short?>("InclinationError")
                        .HasColumnType("smallint");

                    b.Property<short?>("SemiMajorAxisError")
                        .HasColumnType("smallint");

                    b.HasKey("FileId", "LineNo", "EntryNum");

                    b.HasIndex("BodyId");

                    b.HasIndex("BodyId", "GatewayTimestamp");

                    b.ToTable("FileLineBodies", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineBodySignal", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<int>("EntryNum")
                        .HasColumnType("int");

                    b.Property<long?>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<int>("BodySignalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("FileId", "LineNo", "EntryNum");

                    b.HasIndex("BodyId");

                    b.HasIndex("BodySignalId");

                    b.HasIndex("BodyId", "GatewayTimestamp");

                    b.HasIndex("BodySignalId", "GatewayTimestamp");

                    b.ToTable("FileLineBodySignals", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineInfo", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<int?>("BodySignalCount")
                        .HasColumnType("int");

                    b.Property<int?>("GameVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("HasBody")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("HasStation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsBad")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LineLength")
                        .HasColumnType("int");

                    b.Property<int?>("NavRouteSystemCount")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessedVersion")
                        .HasColumnType("int");

                    b.Property<int?>("SchemaEventId")
                        .HasColumnType("int");

                    b.Property<int?>("SignalCount")
                        .HasColumnType("int");

                    b.Property<int?>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Timestamp")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("FileId", "LineNo");

                    b.HasIndex("GameVersionId");

                    b.HasIndex("SchemaEventId");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("SystemId");

                    b.HasIndex("SystemId", "GatewayTimestamp");

                    b.ToTable("FileLineInfo", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineNavRoute", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<int>("EntryNum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("FileId", "LineNo", "EntryNum");

                    b.HasIndex("SystemId");

                    b.HasIndex("SystemId", "GatewayTimestamp");

                    b.ToTable("FileLineNavRoutes", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineSignal", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SignalSetId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("FileId", "LineNo");

                    b.HasIndex("SignalSetId");

                    b.HasIndex("SystemId");

                    b.HasIndex("SignalSetId", "GatewayTimestamp");

                    b.HasIndex("SystemId", "GatewayTimestamp");

                    b.ToTable("FileLineSignals", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineStation", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<short?>("LatitudeError")
                        .HasColumnType("smallint");

                    b.Property<short?>("LongitudeError")
                        .HasColumnType("smallint");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("FileId", "LineNo");

                    b.HasIndex("StationId");

                    b.HasIndex("StationId", "GatewayTimestamp");

                    b.ToTable("FileLineStations", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FilePrefixSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("FilenamePrefix")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsTest")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PrimarySchema")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("FilePrefixSchemas", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.GameVersionDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsAlphaOrBeta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdateEndTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("UpdateStartTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime>("UpdateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GameVersionDates", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.GameVersionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GameBuild")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GameVersion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsHorizons")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsOdyssey")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion", "GameBuild", "IsOdyssey", "IsHorizons");

                    b.ToTable("GameVersions", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.ParentSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodyID")
                        .HasColumnType("int");

                    b.Property<string>("BodyType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ParentJson")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ParentSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentSetId");

                    b.HasIndex("BodyID", "BodyType", "ParentJson");

                    b.HasIndex("BodyID", "BodyType", "ParentSetId");

                    b.ToTable("ParentSets", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SchemaEventInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("FirstSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Schema", "EventType");

                    b.ToTable("SchemaEvents", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("HASectorPriority")
                        .HasColumnType("int");

                    b.Property<bool?>("IsHASector")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("SectorAddress")
                        .HasColumnType("int");

                    b.Property<decimal?>("SizeX")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("SizeY")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("SizeZ")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<decimal?>("X0")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Y0")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Z0")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SectorAddress");

                    b.HasIndex("IsHASector", "Z0", "Y0", "X0");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsStation")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SignalType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("SignalName");

                    b.ToTable("SignalInfo", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfoSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstSignalId")
                        .HasColumnType("int");

                    b.Property<int>("LastSignalId")
                        .HasColumnType("int");

                    b.Property<int>("SignalCount")
                        .HasColumnType("int");

                    b.Property<string>("SignalSetJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FirstSignalId", "LastSignalId", "SignalCount");

                    b.ToTable("SignalInfoSets", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfoSetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("SignalInfoId")
                        .HasColumnType("int");

                    b.Property<int>("SignalInfoSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SignalInfoId");

                    b.HasIndex("SignalInfoSetId");

                    b.ToTable("SignalInfoSetItem", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SoftwareInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareName", "SoftwareVersion");

                    b.ToTable("Software", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.StationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<long?>("MarketId")
                        .HasColumnType("bigint");

                    b.Property<string>("StationName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("StationType")
                        .HasColumnType("longtext");

                    b.Property<long?>("SystemAddress")
                        .HasColumnType("bigint");

                    b.Property<string>("SystemName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("StationName");

                    b.HasIndex("MarketId", "SystemName", "StationName");

                    b.HasIndex("SystemName", "StationName", "MarketId");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsHASystem")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tinyint(1)")
                        .HasComputedColumnSql("`SystemNameId` >= 1 << 60");

                    b.Property<bool?>("IsNamedSystem")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tinyint(1)")
                        .HasComputedColumnSql("`SystemNameId` < 0");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ModSystemAddress")
                        .HasColumnType("bigint");

                    b.Property<long?>("NameModSystemAddress")
                        .HasColumnType("bigint");

                    b.Property<string>("NameSysAddr_PGSuffix")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComputedColumnSql("concat(' ',char((`NameModSystemAddress` >> 16 & 0x1fffff) MOD 26 + 65),char(floor((`NameModSystemAddress` >> 16 & 0x1fffff) / 26 MOD 26) + 65),'-',char(floor((`NameModSystemAddress` >> 16 & 0x1fffff) / (26 * 26) MOD 26) + 65),' ',char((`NameModSystemAddress` >> 37 & 7) + 97),if(floor((`NameModSystemAddress` >> 16 & 0x1fffff) / (26 * 26 * 26)) = 0,'',concat(floor((`NameModSystemAddress` >> 16 & 0x1fffff) / (26 * 26 * 26)),'-')),`NameModSystemAddress` & 65535)");

                    b.Property<int?>("NameSysAddr_SectorAddress")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("`NameModSystemAddress` >> 40");

                    b.Property<string>("PGSuffix")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComputedColumnSql("if(`SystemNameId` >= 0,concat(' ',char((`SystemNameId` >> 16 & 0x1fffff) MOD 26 + 65),char(floor((`SystemNameId` >> 16 & 0x1fffff) / 26 MOD 26) + 65),'-',char(floor((`SystemNameId` >> 16 & 0x1fffff) / (26 * 26) MOD 26) + 65),' ',char((`SystemNameId` >> 37 & 7) + 97),if(floor((`SystemNameId` >> 16 & 0x1fffff) / (26 * 26 * 26)) = 0,'',concat(floor((`SystemNameId` >> 16 & 0x1fffff) / (26 * 26 * 26)),'-')),`SystemNameId` & 65535),NULL)");

                    b.Property<int?>("SectorAddress")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("if(`SystemNameId` > 0 and `SystemNameId` < 1 << 60,`SystemNameId` >> 40,NULL)");

                    b.Property<int?>("SectorId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("if(`SystemNameId` >= 1 << 60,(`SystemNameId` >> 40) - 0x100000,NULL)");

                    b.Property<string>("SysAddr_PGSuffix")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComputedColumnSql("concat(' ',char((`ModSystemAddress` >> 16 & 0x1fffff) MOD 26 + 65),char(floor((`ModSystemAddress` >> 16 & 0x1fffff) / 26 MOD 26) + 65),'-',char(floor((`ModSystemAddress` >> 16 & 0x1fffff) / (26 * 26) MOD 26) + 65),' ',char((`ModSystemAddress` >> 37 & 7) + 97),if(floor((`ModSystemAddress` >> 16 & 0x1fffff) / (26 * 26 * 26)) = 0,'',concat(floor((`ModSystemAddress` >> 16 & 0x1fffff) / (26 * 26 * 26)),'-')),`ModSystemAddress` & 65535)");

                    b.Property<int?>("SysAddr_SectorAddress")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("`ModSystemAddress` >> 40");

                    b.Property<long?>("SystemAddress")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("(`ModSystemAddress` & 0xffff) << 44 - (`ModSystemAddress` >> 37 & 7) * 3 | (`ModSystemAddress` >> 40 & 0x7f) << 37 - (`ModSystemAddress` >> 37 & 7) * 3 | (`ModSystemAddress` >> 16 & 0x7f) << 30 - (`ModSystemAddress` >> 37 & 7) * 2 | (`ModSystemAddress` >> 47 & 0x3f) << 24 - (`ModSystemAddress` >> 37 & 7) * 2 | (`ModSystemAddress` >> 23 & 0x7f) << 17 - (`ModSystemAddress` >> 37 & 7) * 1 | (`ModSystemAddress` >> 53 & 0x7f) << 10 - (`ModSystemAddress` >> 37 & 7) * 1 | (`ModSystemAddress` >> 30 & 0x7f) << 3 | `ModSystemAddress` >> 37 & 7");

                    b.Property<long?>("SystemNameId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<decimal?>("X")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Y")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Z")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("Id");

                    b.HasIndex("ModSystemAddress");

                    b.HasIndex("NameModSystemAddress");

                    b.HasIndex("SystemNameId");

                    b.ToTable("Systems", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SystemName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("SystemNames", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SystemNameOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("SystemAddress")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<decimal?>("X")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Y")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Z")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("Id");

                    b.ToTable("SystemNameOverrides", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodyInfo", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.ParentSet", "ParentSet")
                        .WithMany()
                        .HasForeignKey("ParentSetId");

                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentSet");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileInfo", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.SchemaEventInfo", "PrimarySchemaEvent")
                        .WithMany()
                        .HasForeignKey("PrimarySchemaEventId");

                    b.Navigation("PrimarySchemaEvent");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineBody", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.BodyInfo", "Body")
                        .WithMany()
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineBodySignal", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.BodyInfo", "Body")
                        .WithMany()
                        .HasForeignKey("BodyId");

                    b.HasOne("EddnIndex.Common.Models.BodySignalInfo", "Signal")
                        .WithMany()
                        .HasForeignKey("BodySignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineInfo", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.GameVersionInfo", "GameVersion")
                        .WithMany()
                        .HasForeignKey("GameVersionId");

                    b.HasOne("EddnIndex.Common.Models.SchemaEventInfo", "SchemaEvent")
                        .WithMany()
                        .HasForeignKey("SchemaEventId");

                    b.HasOne("EddnIndex.Common.Models.SoftwareInfo", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId");

                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId");

                    b.Navigation("GameVersion");

                    b.Navigation("SchemaEvent");

                    b.Navigation("Software");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineNavRoute", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineSignal", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.SignalInfoSet", "SignalInfoSet")
                        .WithMany()
                        .HasForeignKey("SignalSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId");

                    b.Navigation("SignalInfoSet");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineStation", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.StationInfo", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.ParentSet", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.ParentSet", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentSetId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfoSetItem", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.SignalInfo", "Signal")
                        .WithMany()
                        .HasForeignKey("SignalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EddnIndex.Common.Models.SignalInfoSet", null)
                        .WithMany("SignalSetItems")
                        .HasForeignKey("SignalInfoSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfoSet", b =>
                {
                    b.Navigation("SignalSetItems");
                });
#pragma warning restore 612, 618
        }
    }
}
