// <auto-generated />
using System;
using EddnIndexUpdate.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EddnIndexUpdate.Migrations_Sqlite.Migrations
{
    [DbContext(typeof(EDDNContext))]
    [Migration("20250905175319_AllowNullBodyIdInParentSet")]
    partial class AllowNullBodyIdInParentSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("EddnIndexUpdate.Models.Body", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ArgOfPeriapsis")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BodyDesignationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BodyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BodyNameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Inclination")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentSetId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SemiMajorAxis")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("SemiMajorAxisScale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SystemNameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BodyNameId");

                    b.HasIndex("ParentSetId");

                    b.HasIndex("SystemId", "BodyId");

                    b.HasIndex("BodyNameId", "SystemId", "ParentSetId");

                    b.ToTable("Bodies", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.BodyDesignation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BarycentreLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClusterNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CometNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DesignationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Moon1Num")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Moon2Num")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Moon3Num")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlanetNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RingNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StarNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StellarBarycentreLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Designation");

                    b.ToTable("BodyDesignations", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.BodyName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("BodyNames", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.BodyNameOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ArgOfPeriapsis")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyDesignation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("BodyID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Inclination")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("SinceVersion")
                        .HasColumnType("TEXT");

                    b.Property<long>("SystemAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UntilVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BodyNameOverrides", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.BodySignalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EntryID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SignalCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SignalType");

                    b.ToTable("BodySignalInfo", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BodyLineCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BodySignalCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompressedSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsTest")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NavRouteSystemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimarySchema")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SignalCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StationLineCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SystemLineCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UncompressedSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("FileName");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineBody", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryNum")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("ArgOfPeriapsisError")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BodyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<short?>("InclinationError")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("SemiMajorAxisError")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId", "LineNo", "EntryNum");

                    b.HasIndex("BodyId");

                    b.ToTable("FileLineBodies", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineBodySignal", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryNum")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BodyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodySignalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("FileId", "LineNo", "EntryNum");

                    b.HasIndex("BodyId");

                    b.HasIndex("BodySignalId");

                    b.ToTable("FileLineBodySignals", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineInfo", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsBad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Timestamp")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.HasKey("FileId", "LineNo");

                    b.HasIndex("GameVersionId");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("SystemId");

                    b.ToTable("FileLineInfo", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineNavRoute", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId", "LineNo", "EntryNum");

                    b.HasIndex("SystemId");

                    b.ToTable("FileLineNavRoutes", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineSignal", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<int>("SignalSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId", "LineNo");

                    b.HasIndex("SignalSetId");

                    b.HasIndex("SystemId");

                    b.ToTable("FileLineSignals", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineStation", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<short?>("LatitudeError")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("LongitudeError")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId", "LineNo");

                    b.HasIndex("StationId");

                    b.ToTable("FileLineStations", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FilePrefixSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilenamePrefix")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimarySchema")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FilePrefixSchemas", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.GameVersionDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsAlphaOrBeta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateEndTime")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateStartTime")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateTime")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameVersionDates", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.GameVersionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameBuild")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsHorizons")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsOdyssey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion", "GameBuild", "IsOdyssey", "IsHorizons");

                    b.ToTable("GameVersions", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.ParentSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BodyID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentJson")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentSetId");

                    b.HasIndex("BodyID", "BodyType", "ParentJson");

                    b.HasIndex("BodyID", "BodyType", "ParentSetId");

                    b.ToTable("ParentSets", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HASectorPriority")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsHASector")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SectorAddress")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SizeX")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SizeY")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SizeZ")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("X0")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Y0")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Z0")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SectorAddress");

                    b.HasIndex("IsHASector", "Z0", "Y0", "X0");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.SignalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsStation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SignalName");

                    b.ToTable("SignalInfo", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.SignalInfoSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstSignalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSignalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignalCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignalSetJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstSignalId", "LastSignalId", "SignalCount");

                    b.ToTable("SignalInfoSets", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.SoftwareInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareName", "SoftwareVersion");

                    b.ToTable("Software", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MarketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationType")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SystemAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationName");

                    b.HasIndex("MarketId", "SystemName", "StationName");

                    b.HasIndex("SystemName", "StationName", "MarketId");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsHASystem")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsNamedSystem")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ModSystemAddress")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NameModSystemAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameSysAddr_PGSuffix")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NameSysAddr_SectorAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PGSuffix")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SectorAddress")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SysAddr_PGSuffix")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SysAddr_SectorAddress")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SystemAddress")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SystemNameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("X")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Y")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Z")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModSystemAddress");

                    b.HasIndex("NameModSystemAddress");

                    b.HasIndex("SystemNameId");

                    b.ToTable("Systems", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.SystemName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("SystemNames", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.SystemNameOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("SystemAddress")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("X")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Y")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Z")
                        .HasPrecision(12, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemNameOverrides", (string)null);
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.Body", b =>
                {
                    b.HasOne("EddnIndexUpdate.Models.ParentSet", "ParentSet")
                        .WithMany()
                        .HasForeignKey("ParentSetId");

                    b.HasOne("EddnIndexUpdate.Models.System", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentSet");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineBody", b =>
                {
                    b.HasOne("EddnIndexUpdate.Models.Body", "Body")
                        .WithMany()
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineBodySignal", b =>
                {
                    b.HasOne("EddnIndexUpdate.Models.Body", "Body")
                        .WithMany()
                        .HasForeignKey("BodyId");

                    b.HasOne("EddnIndexUpdate.Models.BodySignalInfo", "Signal")
                        .WithMany()
                        .HasForeignKey("BodySignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineInfo", b =>
                {
                    b.HasOne("EddnIndexUpdate.Models.GameVersionInfo", "GameVersion")
                        .WithMany()
                        .HasForeignKey("GameVersionId");

                    b.HasOne("EddnIndexUpdate.Models.SoftwareInfo", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId");

                    b.HasOne("EddnIndexUpdate.Models.System", "System")
                        .WithMany()
                        .HasForeignKey("SystemId");

                    b.Navigation("GameVersion");

                    b.Navigation("Software");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineNavRoute", b =>
                {
                    b.HasOne("EddnIndexUpdate.Models.System", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineSignal", b =>
                {
                    b.HasOne("EddnIndexUpdate.Models.SignalInfoSet", "SignalInfoSet")
                        .WithMany()
                        .HasForeignKey("SignalSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EddnIndexUpdate.Models.System", "System")
                        .WithMany()
                        .HasForeignKey("SystemId");

                    b.Navigation("SignalInfoSet");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.FileLineStation", b =>
                {
                    b.HasOne("EddnIndexUpdate.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.ParentSet", b =>
                {
                    b.HasOne("EddnIndexUpdate.Models.ParentSet", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentSetId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EddnIndexUpdate.Models.SignalInfoSet", b =>
                {
                    b.OwnsMany("EddnIndexUpdate.Models.SignalInfoSetItem", "SignalSetItems", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Count")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SignalInfoId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SignalInfoSetId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("SignalInfoId");

                            b1.HasIndex("SignalInfoSetId");

                            b1.ToTable("SignalInfoSetItem");

                            b1.HasOne("EddnIndexUpdate.Models.SignalInfo", "Signal")
                                .WithMany()
                                .HasForeignKey("SignalInfoId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SignalInfoSetId");

                            b1.Navigation("Signal");
                        });

                    b.Navigation("SignalSetItems");
                });
#pragma warning restore 612, 618
        }
    }
}
