// <auto-generated />
using System;
using EddnIndex.Common.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EddnIndexUpdate.Migrations_SqlServer.Migrations
{
    [DbContext(typeof(EDDNContext))]
    [Migration("20260716065527_AddSignalItemFirstLastSeen")]
    partial class AddSignalItemFirstLastSeen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EddnIndex.Common.Models.BodyDesignation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BarycentreLength")
                        .HasColumnType("int");

                    b.Property<int?>("ClusterNum")
                        .HasColumnType("int");

                    b.Property<int?>("CometNum")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("DesignationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Moon1Num")
                        .HasColumnType("int");

                    b.Property<int?>("Moon2Num")
                        .HasColumnType("int");

                    b.Property<int?>("Moon3Num")
                        .HasColumnType("int");

                    b.Property<int?>("PlanetNum")
                        .HasColumnType("int");

                    b.Property<int?>("RingNum")
                        .HasColumnType("int");

                    b.Property<int?>("StarNum")
                        .HasColumnType("int");

                    b.Property<int?>("StellarBarycentreLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Designation");

                    b.ToTable("BodyDesignations", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodyInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ArgOfPeriapsis")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("BodyDesignationId")
                        .HasColumnType("int");

                    b.Property<int?>("BodyId")
                        .HasColumnType("int");

                    b.Property<int>("BodyNameId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<decimal?>("Inclination")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<int?>("ParentSetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SemiMajorAxis")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<short>("SemiMajorAxisScale")
                        .HasColumnType("smallint");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.Property<long?>("SystemNameId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("BodyNameId");

                    b.HasIndex("ParentSetId");

                    b.HasIndex("SystemId", "BodyId");

                    b.HasIndex("BodyNameId", "SystemId", "ParentSetId");

                    b.ToTable("Bodies", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodyName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("BodyNames", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodyNameOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ArgOfPeriapsis")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<string>("BodyDesignation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("BodyID")
                        .HasColumnType("int");

                    b.Property<string>("BodyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BodyType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Inclination")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<string>("SinceVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SystemAddress")
                        .HasColumnType("bigint");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UntilVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.ToTable("BodyNameOverrides", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodySignalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("EntryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SignalCount")
                        .HasColumnType("int");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("SignalType");

                    b.ToTable("BodySignalInfo", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodyLineCount")
                        .HasColumnType("int");

                    b.Property<int?>("BodySignalCount")
                        .HasColumnType("int");

                    b.Property<long?>("CompressedSize")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("IsTest")
                        .HasColumnType("bit");

                    b.Property<int?>("LineCount")
                        .HasColumnType("int");

                    b.Property<int?>("NavRouteSystemCount")
                        .HasColumnType("int");

                    b.Property<string>("PrimarySchema")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("PrimarySchemaEventId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessedVersion")
                        .HasColumnType("int");

                    b.Property<int?>("SignalCount")
                        .HasColumnType("int");

                    b.Property<int?>("StationLineCount")
                        .HasColumnType("int");

                    b.Property<int?>("SystemLineCount")
                        .HasColumnType("int");

                    b.Property<long?>("UncompressedSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("FileName");

                    b.HasIndex("PrimarySchemaEventId");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineBody", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<int>("EntryNum")
                        .HasColumnType("int");

                    b.Property<short?>("ArgOfPeriapsisError")
                        .HasColumnType("smallint");

                    b.Property<long>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<short?>("InclinationError")
                        .HasColumnType("smallint");

                    b.Property<short?>("SemiMajorAxisError")
                        .HasColumnType("smallint");

                    b.HasKey("FileId", "LineNo", "EntryNum");

                    b.HasIndex("BodyId");

                    b.HasIndex("BodyId", "GatewayTimestamp");

                    b.ToTable("FileLineBodies", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineBodySignal", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<int>("EntryNum")
                        .HasColumnType("int");

                    b.Property<long?>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<int>("BodySignalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("FileId", "LineNo", "EntryNum");

                    b.HasIndex("BodyId");

                    b.HasIndex("BodySignalId");

                    b.HasIndex("BodyId", "GatewayTimestamp");

                    b.HasIndex("BodySignalId", "GatewayTimestamp");

                    b.ToTable("FileLineBodySignals", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineInfo", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<int?>("BodySignalCount")
                        .HasColumnType("int");

                    b.Property<int?>("GameVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<bool?>("HasBody")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasStation")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBad")
                        .HasColumnType("bit");

                    b.Property<int>("LineLength")
                        .HasColumnType("int");

                    b.Property<int?>("NavRouteSystemCount")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessedVersion")
                        .HasColumnType("int");

                    b.Property<int?>("SchemaEventId")
                        .HasColumnType("int");

                    b.Property<int?>("SignalCount")
                        .HasColumnType("int");

                    b.Property<int?>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Timestamp")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("FileId", "LineNo");

                    b.HasIndex("GameVersionId");

                    b.HasIndex("SchemaEventId");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("SystemId");

                    b.HasIndex("SystemId", "GatewayTimestamp");

                    b.ToTable("FileLineInfo", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineNavRoute", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<int>("EntryNum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("FileId", "LineNo", "EntryNum");

                    b.HasIndex("SystemId");

                    b.HasIndex("SystemId", "GatewayTimestamp");

                    b.ToTable("FileLineNavRoutes", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineSignal", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<int>("SignalSetId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("FileId", "LineNo");

                    b.HasIndex("SignalSetId");

                    b.HasIndex("SystemId");

                    b.HasIndex("SignalSetId", "GatewayTimestamp");

                    b.HasIndex("SystemId", "GatewayTimestamp");

                    b.ToTable("FileLineSignals", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineStation", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<short?>("LatitudeError")
                        .HasColumnType("smallint");

                    b.Property<short?>("LongitudeError")
                        .HasColumnType("smallint");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("FileId", "LineNo");

                    b.HasIndex("StationId");

                    b.HasIndex("StationId", "GatewayTimestamp");

                    b.ToTable("FileLineStations", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FilePrefixSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FilenamePrefix")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit");

                    b.Property<string>("PrimarySchema")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("FilePrefixSchemas", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.GameVersionDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsAlphaOrBeta")
                        .HasColumnType("bit");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateEndTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("UpdateStartTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("UpdateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GameVersionDates", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.GameVersionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("GameBuild")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GameVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsHorizons")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOdyssey")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion", "GameBuild", "IsOdyssey", "IsHorizons");

                    b.ToTable("GameVersions", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.ParentSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodyID")
                        .HasColumnType("int");

                    b.Property<string>("BodyType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParentJson")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentSetId");

                    b.HasIndex("BodyID", "BodyType", "ParentJson");

                    b.HasIndex("BodyID", "BodyType", "ParentSetId");

                    b.ToTable("ParentSets", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SchemaEventInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Schema", "EventType");

                    b.ToTable("SchemaEvents", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<int?>("HASectorPriority")
                        .HasColumnType("int");

                    b.Property<bool?>("IsHASector")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("SectorAddress")
                        .HasColumnType("int");

                    b.Property<decimal?>("SizeX")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("SizeY")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("SizeZ")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal?>("X0")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Y0")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Z0")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SectorAddress");

                    b.HasIndex("IsHASector", "Z0", "Y0", "X0");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<bool?>("IsStation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SignalType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("SignalName");

                    b.ToTable("SignalInfo", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfoSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstSignalId")
                        .HasColumnType("int");

                    b.Property<int>("LastSignalId")
                        .HasColumnType("int");

                    b.Property<int>("SignalCount")
                        .HasColumnType("int");

                    b.Property<string>("SignalSetJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.HasIndex("FirstSignalId", "LastSignalId", "SignalCount");

                    b.ToTable("SignalInfoSets", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfoSetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<int>("SignalInfoId")
                        .HasColumnType("int");

                    b.Property<int>("SignalInfoSetId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SignalInfoId");

                    b.HasIndex("SignalInfoSetId");

                    b.HasIndex("SystemId");

                    b.HasIndex("SignalInfoId", "SystemId");

                    b.HasIndex("SignalInfoId", "LastSeen", "FirstSeen", "SystemId");

                    b.ToTable("SignalInfoSetItem", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SoftwareInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareName", "SoftwareVersion");

                    b.ToTable("Software", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.StationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<long?>("MarketId")
                        .HasColumnType("bigint");

                    b.Property<string>("StationName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SystemAddress")
                        .HasColumnType("bigint");

                    b.Property<string>("SystemName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("StationName");

                    b.HasIndex("MarketId", "SystemName", "StationName");

                    b.HasIndex("SystemName", "StationName", "MarketId");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<bool?>("IsHASystem")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("CAST(IIF(SystemNameId >= 0x1000000000000000, 1, 0) AS BIT)");

                    b.Property<bool?>("IsNamedSystem")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("CAST(IIF(SystemNameId < 0, 1, 0) AS BIT)");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<long?>("ModSystemAddress")
                        .HasColumnType("bigint");

                    b.Property<long?>("NameModSystemAddress")
                        .HasColumnType("bigint");

                    b.Property<string>("NameSysAddr_PGSuffix")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONCAT(' ',CHAR((NameModSystemAddress >> 16 & 0x1FFFFF) % 26 + 65),CHAR(FLOOR((NameModSystemAddress >> 16 & 0x1FFFFF) / 26) % 26 + 65),'-',CHAR(FLOOR((NameModSystemAddress >> 16 & 0x1FFFFF) / (26 * 26)) % 26 + 65),' ',CHAR(NameModSystemAddress >> 37 & 7 + 97),IIF(FLOOR((NameModSystemAddress >> 16 & 0x1FFFFF) / (26 * 26 * 26)) > 0,CONCAT(FLOOR((NameModSystemAddress >> 16 & 0x1FFFFF) / (26 * 26 * 26)), '-'),''),NameModSystemAddress & 0xFFFF)");

                    b.Property<int?>("NameSysAddr_SectorAddress")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CAST(NameModSystemAddress >> 40 AS INT)");

                    b.Property<string>("PGSuffix")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("IIF(SystemNameId >= 0,CONCAT(' ',CHAR((SystemNameId >> 16 & 0x1FFFFF) % 26 + 65),CHAR(FLOOR((SystemNameId >> 16 & 0x1FFFFF) / 26) % 26 + 65),'-',CHAR(FLOOR((SystemNameId >> 16 & 0x1FFFFF) / (26 * 26)) % 26 + 65),' ',CHAR(SystemNameId >> 37 & 7 + 97),IIF(FLOOR((SystemNameId >> 16 & 0x1FFFFF) / (26 * 26 * 26)) > 0,CONCAT(FLOOR((SystemNameId >> 16 & 0x1FFFFF) / (26 * 26 * 26)), '-'),''),SystemNameId & 0xFFFF),NULL)");

                    b.Property<int?>("SectorAddress")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CAST(IIF(SystemNameId >= 0 AND SystemNameId < 0x1000000000000000, (SystemNameId >> 40), NULL) AS INT)");

                    b.Property<int?>("SectorId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CAST(IIF(SystemNameId >= 0x1000000000000000, (SystemNameId >> 40) - 0x100000, NULL) AS INT)");

                    b.Property<string>("SysAddr_PGSuffix")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONCAT(' ',CHAR((ModSystemAddress >> 16 & 0x1FFFFF) % 26 + 65),CHAR(FLOOR((ModSystemAddress >> 16 & 0x1FFFFF) / 26) % 26 + 65),'-',CHAR(FLOOR((ModSystemAddress >> 16 & 0x1FFFFF) / (26 * 26)) % 26 + 65),' ',CHAR(ModSystemAddress >> 37 & 7 + 97),IIF(FLOOR((ModSystemAddress >> 16 & 0x1FFFFF) / (26 * 26 * 26)) > 0,CONCAT(FLOOR((ModSystemAddress >> 16 & 0x1FFFFF) / (26 * 26 * 26)), '-'),''),ModSystemAddress & 0xFFFF)");

                    b.Property<int?>("SysAddr_SectorAddress")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CAST(ModSystemAddress >> 40 AS INT)");

                    b.Property<long?>("SystemAddress")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("((ModSystemAddress & 0xFFFF) << (44 - (ModSystemAddress >> 37 & 7) * 3)) | ((ModSystemAddress >> 40 & 0x7F) << (37 - (ModSystemAddress >> 37 & 7) * 3)) | ((ModSystemAddress >> 16 & 0x7F) << (30 - (ModSystemAddress >> 37 & 7) * 2)) | ((ModSystemAddress >> 47 & 0x3F) << (24 - (ModSystemAddress >> 37 & 7) * 2)) | ((ModSystemAddress >> 23 & 0x7F) << (17 - (ModSystemAddress >> 37 & 7) * 1)) | ((ModSystemAddress >> 53 & 0x7F) << (10 - (ModSystemAddress >> 37 & 7) * 1)) | ((ModSystemAddress >> 16 & 0x7F) << 3) | (ModSystemAddress >> 37 & 7)");

                    b.Property<long?>("SystemNameId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal?>("X")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Y")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Z")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("Id");

                    b.HasIndex("ModSystemAddress");

                    b.HasIndex("NameModSystemAddress");

                    b.HasIndex("SystemNameId");

                    b.ToTable("Systems", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SystemName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("SystemNames", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SystemNameOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SystemAddress")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ValidTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal?>("X")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Y")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("Z")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("Id");

                    b.ToTable("SystemNameOverrides", (string)null);
                });

            modelBuilder.Entity("EddnIndex.Common.Models.BodyInfo", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.ParentSet", "ParentSet")
                        .WithMany()
                        .HasForeignKey("ParentSetId");

                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentSet");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileInfo", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.SchemaEventInfo", "PrimarySchemaEvent")
                        .WithMany()
                        .HasForeignKey("PrimarySchemaEventId");

                    b.Navigation("PrimarySchemaEvent");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineBody", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.BodyInfo", "Body")
                        .WithMany()
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineBodySignal", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.BodyInfo", "Body")
                        .WithMany()
                        .HasForeignKey("BodyId");

                    b.HasOne("EddnIndex.Common.Models.BodySignalInfo", "Signal")
                        .WithMany()
                        .HasForeignKey("BodySignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineInfo", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.GameVersionInfo", "GameVersion")
                        .WithMany()
                        .HasForeignKey("GameVersionId");

                    b.HasOne("EddnIndex.Common.Models.SchemaEventInfo", "SchemaEvent")
                        .WithMany()
                        .HasForeignKey("SchemaEventId");

                    b.HasOne("EddnIndex.Common.Models.SoftwareInfo", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId");

                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId");

                    b.Navigation("GameVersion");

                    b.Navigation("SchemaEvent");

                    b.Navigation("Software");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineNavRoute", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineSignal", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.SignalInfoSet", "SignalInfoSet")
                        .WithMany()
                        .HasForeignKey("SignalSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId");

                    b.Navigation("SignalInfoSet");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.FileLineStation", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.StationInfo", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.ParentSet", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.ParentSet", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentSetId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfoSet", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfoSetItem", b =>
                {
                    b.HasOne("EddnIndex.Common.Models.SignalInfo", "Signal")
                        .WithMany()
                        .HasForeignKey("SignalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EddnIndex.Common.Models.SignalInfoSet", null)
                        .WithMany("SignalSetItems")
                        .HasForeignKey("SignalInfoSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EddnIndex.Common.Models.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId");

                    b.Navigation("Signal");

                    b.Navigation("System");
                });

            modelBuilder.Entity("EddnIndex.Common.Models.SignalInfoSet", b =>
                {
                    b.Navigation("SignalSetItems");
                });
#pragma warning restore 612, 618
        }
    }
}
